# What is Data Science?
#It includes data collecting, data cleansing, data analysis, data visualization, data prediction and much more.
#With exponential digitalization, humongous amounts of data is being generated. 
#But, data in itself is of no use; it becomes useful with Data Science which derives meaningful insights from data.


# What is Machine Learning?
#Machine Learning is a sub-set or an implementation of Artificial Intelligence. 
#Machine Learning refers to the practice of using various techniques and algorithms to extract data, analyse it, 
   learn from it, and then forecast future trends for making better business decisions. 
#Machine Learning has various algorithms like simple linear regression, decision tree regression,
   K-nearest neighbors etc. which are used for clarification problems, clustering problems etc.


# What is Deep Learning?
Deep Learning is an advancement of Machine Learning. It is based on various artificial neural networks. 
It is a function that processes data to mimic the human brain so as to enable machines in detecting objects,
recognizing speeches, translating languages and a lot more.
It is believed that Machine Learning comes in handy when the amount of data given is small, 
but Deep Learning is your one stop solution while working on a huge amount of data with distinctive features.
It is also important to not that Deep Learning is more difficult to implement as compared to Machine Learning because 
it requires more training time and a much more powerful hardware to work on.


## What is AI?
AI is a branch of Computer Sciences that deals with the capability of teaching machines to learn and 
imitate human behaviors and pattern. 
AI is a type of neural networks constructed on various algorithms designed to prepare machines 
in a way that they assist humans in all their everyday jobs by learning human behavior.


In [ ]:
### Python Basic Data Types


##  What is NumPy?

### NumPy is a Python library used for working with arrays.

### It also has functions for working in domain of linear algebra, fourier transform, and matrices.

### NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

### NumPy stands for Numerical Python.

# Why Use NumPy?

### In Python we have lists that serve the purpose of arrays, but they are slow to process.

### NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

### The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

### Arrays are very frequently used in data science, where speed and resources are very important.
    

# Numpy: Package for Multidimensional array
## Vector(1d)
### Matrix(2d or 1d)

In [1]:
import numpy as np

In [2]:
simple_list=[1,2,3,"a"]
simple_list

[1, 2, 3, 'a']

In [3]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [4]:
list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
np.arange(5,20)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [9]:
np.arange(21,71,5,dtype=float)

array([21., 26., 31., 36., 41., 46., 51., 56., 61., 66.])

In [11]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [15]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
np.linspace(0,20,19)

In [19]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
np.random.randn(2,3)

array([[-1.35827811, -0.34606452,  0.95462677],
       [-1.00059754, -0.62164972,  0.68121716]])

In [25]:
np.random.rand(5,4)

array([[0.93326999, 0.81147522, 0.69945363, 0.89362794],
       [0.92794742, 0.25300457, 0.16327909, 0.23324909],
       [0.79687101, 0.51303958, 0.58859377, 0.22759453],
       [0.49570204, 0.43375815, 0.71500846, 0.76541102],
       [0.5385908 , 0.02978761, 0.98647216, 0.00152742]])

In [30]:
np.random.randint(1,10)

9

In [31]:
np.random.randint(20,28,100)

array([23, 26, 23, 21, 24, 24, 24, 26, 26, 23, 21, 26, 26, 21, 22, 23, 26,
       24, 20, 25, 26, 26, 26, 26, 22, 22, 27, 21, 20, 22, 23, 22, 21, 23,
       23, 27, 23, 25, 23, 23, 23, 20, 22, 21, 25, 25, 24, 23, 24, 27, 21,
       21, 25, 20, 25, 26, 23, 26, 24, 26, 22, 23, 22, 27, 26, 23, 25, 24,
       20, 21, 24, 25, 26, 24, 24, 20, 23, 25, 24, 24, 23, 21, 24, 22, 21,
       22, 27, 22, 23, 20, 22, 22, 27, 23, 23, 21, 26, 21, 22, 23])

In [32]:
sample_array=np.arange(50)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [33]:
rand_array=np.random.randint(0,100,20)
rand_array

array([67, 57, 28, 26, 28, 90,  9, 32, 16, 73, 26, 70, 25, 12, 86, 47, 28,
        7, 22, 23])

In [34]:
rand_array.reshape(5,4)

array([[67, 57, 28, 26],
       [28, 90,  9, 32],
       [16, 73, 26, 70],
       [25, 12, 86, 47],
       [28,  7, 22, 23]])

In [36]:
rand_array.reshape(2,10)

array([[67, 57, 28, 26, 28, 90,  9, 32, 16, 73],
       [26, 70, 25, 12, 86, 47, 28,  7, 22, 23]])

In [37]:
df=sample_array.reshape(5,10)
df

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [38]:
rand_array.max()

90

In [39]:
sample_array.min()

0

In [40]:
rand_array.argmin()

17

In [41]:
rand_array.argmax()

5

In [42]:
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [43]:
sample_array.shape

(50,)

In [ ]:
sample_array.reshape(5,10)

In [44]:
sample_array.dtype

dtype('int32')

In [45]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [46]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [47]:
a=np.random.rand(2,3)
a

array([[0.31925938, 0.24587446, 0.10064487],
       [0.75212345, 0.83881186, 0.17351052]])

In [48]:
a.T

array([[0.31925938, 0.75212345],
       [0.24587446, 0.83881186],
       [0.10064487, 0.17351052]])

In [ ]:
import numpy as np

In [49]:
sample_array=np.arange(1,51)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [50]:
df1=sample_array.reshape(10,5)
df1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [ ]:
sample_array=np.arange(10,21)
sample_array

In [ ]:
sample_array[0:7]

In [ ]:
subset_sample_array=sample_array[0:7]
subset_sample_array

In [ ]:
sample_array[2:8]=100
sample_array

### Two-Dimensional array

In [51]:
sample_matrix=np.array(([50,20,1,23],[24,23,21,33],[56,76,24,7]))
sample_matrix

array([[50, 20,  1, 23],
       [24, 23, 21, 33],
       [56, 76, 24,  7]])

In [52]:
sample_matrix[0][3]

23

In [53]:
sample_matrix[:,0]

array([50, 24, 56])

In [54]:
sample_matrix[1,1:3]

array([23, 21])

In [55]:
sample_matrix[2]

array([56, 76, 24,  7])

In [56]:
sample_matrix[:,2]

array([ 1, 21, 24])

### Custom indexing

In [57]:
sample_matrix=np.array(([50,20,1,23],[24,23,21,33],[56,76,24,7]))
sample_matrix

array([[50, 20,  1, 23],
       [24, 23, 21, 33],
       [56, 76, 24,  7]])

In [58]:
sample_matrix[0:2,(2,3)]

array([[ 1, 23],
       [21, 33]])

###  Selection techniques

In [59]:
sample_array=np.arange(1,11)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [60]:
bool=sample_array<6
bool

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [61]:
sample_array[bool]

array([1, 2, 3, 4, 5])

In [62]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [63]:
np.exp(sample_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [64]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [65]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [66]:
np.max(sample_array)

10

In [67]:
np.min(sample_array)

1

In [68]:
np.argmax(sample_array)

9

In [69]:
np.argmin(sample_array)

0

In [70]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [71]:
np.std(sample_array)

2.8722813232690143

In [72]:
np.var(sample_array)


8.25

In [73]:
np.mean(sample_array)

5.5

In [74]:
array=np.random.randn(3,5)
array

array([[ 8.99651020e-02,  1.68204858e+00, -1.91096895e+00,
        -5.73718392e-01,  1.26097343e+00],
       [-1.36539159e-03, -8.38475744e-01, -9.88393848e-01,
         6.47356377e-01, -2.11308286e-01],
       [ 5.89402502e-01,  3.17563820e-01,  1.03712686e+00,
        -1.49574750e+00,  1.10294630e+00]])

In [76]:
np.round(array,decimals=3)

array([[ 9.000e-02,  1.682e+00, -1.911e+00, -5.740e-01,  1.261e+00],
       [-1.000e-03, -8.380e-01, -9.880e-01,  6.470e-01, -2.110e-01],
       [ 5.890e-01,  3.180e-01,  1.037e+00, -1.496e+00,  1.103e+00]])

In [78]:
sports=np.array(['golf','cric','fball','cric','cric','fball'])
np.unique(sports)

array(['cric', 'fball', 'golf'], dtype='<U5')

In [79]:
import numpy as np

In [1]:
import pandas as pd

In [4]:
labels=['w','x','y','z']
list=[10,20,30,40]
array=np.array([10,20,30,40])
dict={'w':10,'x':20,'y':30,'z':40}


In [6]:
pd.Series(data=labels)

0    w
1    x
2    y
3    z
dtype: object

In [7]:
pd.Series(data=list,index=labels)

w    10
x    20
y    30
z    40
dtype: int64

In [9]:
pd.Series(array,labels)

w    10
x    20
y    30
z    40
dtype: int32

In [10]:
pd.Series(dict)

w    10
x    20
y    30
z    40
dtype: int64

### Pandas dataframe and indexing

In [11]:
sports1=pd.Series([1,2,3,4,5],index=['cricket','football','basketball','golf','baseball'])
sports1

cricket       1
football      2
basketball    3
golf          4
baseball      5
dtype: int64

In [15]:
sports1['golf']

4

In [21]:
sports2=pd.Series([11,2,4],index=['cricket','baseball','golf'])
sports2

cricket     11
baseball     2
golf         4
dtype: int64

In [22]:
sports1+sports2

baseball       7.0
basketball     NaN
cricket       12.0
football       NaN
golf           8.0
dtype: float64

In [27]:
##from numpy.random import randn


In [31]:
df1=pd.DataFrame(np.random.randn(8,5),index='A B C D E F G H'.split(),columns='Score1 Score2 Score3 Score4 Score5'.split())
df1

Score1    Score2    Score3    Score4    Score5
A -0.384530 -0.968987  0.338469 -0.400618  1.509678
B -0.569697 -0.753076 -0.435247  0.438718 -0.931895
C -0.547350 -0.590381  0.976574 -0.523335 -0.443315
D -1.302607  0.077783 -1.061692  1.702793 -1.371185
E -0.771949 -0.154973  1.143592  1.551411  0.061238
F -1.411649  1.066630  0.214722  1.551523 -1.242378
G -0.322189 -1.083185 -1.454699  0.321005 -1.583343
H -0.827502  0.456961  0.651122 -1.151334  0.637979

In [38]:
df1[['Score1']]

Score1
A -0.384530
B -0.569697
C -0.547350
D -1.302607
E -0.771949
F -1.411649
G -0.322189
H -0.827502

In [42]:
df1[['Score2','Score1','Score3']]

Score2    Score1    Score3
A -0.968987 -0.384530  0.338469
B -0.753076 -0.569697 -0.435247
C -0.590381 -0.547350  0.976574
D  0.077783 -1.302607 -1.061692
E -0.154973 -0.771949  1.143592
F  1.066630 -1.411649  0.214722
G -1.083185 -0.322189 -1.454699
H  0.456961 -0.827502  0.651122

In [45]:
df1['Score6']=df1['Score1']+df1['Score2']
df1

Score1    Score2    Score3    Score4    Score5    Score6
A -0.384530 -0.968987  0.338469 -1.353517  1.509678 -1.353517
B -0.569697 -0.753076 -0.435247 -1.322774 -0.931895 -1.322774
C -0.547350 -0.590381  0.976574 -1.137731 -0.443315 -1.137731
D -1.302607  0.077783 -1.061692 -1.224823 -1.371185 -1.224823
E -0.771949 -0.154973  1.143592 -0.926922  0.061238 -0.926922
F -1.411649  1.066630  0.214722 -0.345019 -1.242378 -0.345019
G -0.322189 -1.083185 -1.454699 -1.405373 -1.583343 -1.405373
H -0.827502  0.456961  0.651122 -0.370541  0.637979 -0.370541

In [55]:
df=df1.drop('Score1',axis=1)
df

Score2    Score3    Score4    Score5    Score6
A -0.968987  0.338469 -1.353517  1.509678 -1.353517
B -0.753076 -0.435247 -1.322774 -0.931895 -1.322774
C -0.590381  0.976574 -1.137731 -0.443315 -1.137731
D  0.077783 -1.061692 -1.224823 -1.371185 -1.224823
E -0.154973  1.143592 -0.926922  0.061238 -0.926922
F  1.066630  0.214722 -0.345019 -1.242378 -0.345019
G -1.083185 -1.454699 -1.405373 -1.583343 -1.405373
H  0.456961  0.651122 -0.370541  0.637979 -0.370541

In [53]:
df.drop('D',axis=0)

Score2    Score3    Score4    Score5    Score6
A -0.968987  0.338469 -1.353517  1.509678 -1.353517
B -0.753076 -0.435247 -1.322774 -0.931895 -1.322774
C -0.590381  0.976574 -1.137731 -0.443315 -1.137731
E -0.154973  1.143592 -0.926922  0.061238 -0.926922
F  1.066630  0.214722 -0.345019 -1.242378 -0.345019
G -1.083185 -1.454699 -1.405373 -1.583343 -1.405373
H  0.456961  0.651122 -0.370541  0.637979 -0.370541

In [54]:
df1.reset_index()

index    Score1    Score2    Score3    Score4    Score5    Score6
0     A -0.384530 -0.968987  0.338469 -1.353517  1.509678 -1.353517
1     B -0.569697 -0.753076 -0.435247 -1.322774 -0.931895 -1.322774
2     C -0.547350 -0.590381  0.976574 -1.137731 -0.443315 -1.137731
3     D -1.302607  0.077783 -1.061692 -1.224823 -1.371185 -1.224823
4     E -0.771949 -0.154973  1.143592 -0.926922  0.061238 -0.926922
5     F -1.411649  1.066630  0.214722 -0.345019 -1.242378 -0.345019
6     G -0.322189 -1.083185 -1.454699 -1.405373 -1.583343 -1.405373
7     H -0.827502  0.456961  0.651122 -0.370541  0.637979 -0.370541

In [67]:
df2={'ID':[101,102,103,107,176],'Profit':[23,54,56,87,67],'Name':['John','Mercy','Akash','Kavin','Lally']}
df=pd.DataFrame(df2)
df

ID  Profit   Name
0  101      23   John
1  102      54  Mercy
2  103      56  Akash
3  107      87  Kavin
4  176      67  Lally